# Generated by Django 2.2 on 2019-08-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tktapp', '0010_auto_20190809_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='select_seat',
            field=models.CharField(choices=[('₹100', (('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'))), ('₹70', (('F', 'F'), ('G', 'G'), ('H', 'H')))], max_length=30),
        ),
    ]
